/* automatically generated by rust-bindgen 0.70.1 */
// pub type __m128i = [::std::os::raw::c_longlong; 2usize];
use std::arch::x86_64::{__m128i};


#[link(name = "libminiaes", kind = "static")]
extern "C" {
    pub fn expand_key(keys: *mut __m128i, key: *const ::std::os::raw::c_uchar);
    pub fn encrypt(key: *const __m128i, in_: *mut __m128i);
    pub fn decrypt(key: *const __m128i, in_: *mut __m128i);
}
